// export const GET_ERRORS = "GET_ERRORS";
// export const USER_LOADING = "USER_LOADING";
// export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_SIGNUP = 'HANDLE_SIGNUP';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';

export const CONNECT_BANK = 'CONNECT_BANK';

export const GET_BALANCE_AND_TRANSACTIONS = 'GET_BALANCE_AND_TRANSACTIONS';
export const GET_BALANCE_GRAPH_DATA = 'GET_BALANCE_GRAPH_DATA'; 

export const UPDATE_OVERDRAFT_NOTIFICATION = 'UPDATE_OVERDRAFT_NOTIFICATION'; 
export const UPDATE_BIG_TRANSACTION_NOTIFICATION = 'UPDATE_BIG_TRANSACTION_NOTIFICATION';
export const UPDATE_MINIMUM_BALANCE_NOTIFICATION = 'UPDATE_MINIMUM_BALANCE_NOTIFICATION';

export const ADD_BILL = 'ADD_BILL';
export const ADD_GOAL_UPDATE_USER = 'ADD_GOAL_UPDATE_USER';
export const FETCH_GOAL_UPDATE_USER = 'FETCH_GOAL_UPDATE_USER';

export const GET_USER = 'GET_USER'; 


export const HANDLE_ERROR = 'HANDLE_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const LOAD_DATA = 'SAVE_DATA';
